global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:80']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
